// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zgfpnvtnbmjiodgmhiho.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpnZnBudnRuYm1qaW9kZ21oaWhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2MzAyNDAsImV4cCI6MjA2NzIwNjI0MH0.RbuloQM4kDLAP6c6fN_wk4D-PhiijlBICgfhd1CYL48";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});